config/routes.rb
Rails.application.routes.draw do
  devise_for :sign_ups
  resources :orders
  resources :clients
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :volunteers
  root 'home#index'
  get "home/about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    after_create { MagicLinkMailer.magic_link(self).deliver }
end

app/models/sign_up.rb
class SignUp < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base

  private

    def client_params
      params.require(:client).permit(:Jméno, :Příjmení, :Město, :Ulice, :ČP, :PSČ, :Poznámka)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Žádost byla odeslána." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def order_params
    params.require(:order).permit(:Jméno, :Příjmení, :Město, :Ulice, :ČP, :PSČ, :Žádost, :Poznámka)
  end
  
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end

end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: %i[ show edit update destroy ]

  # GET /volunteers/1 or /volunteers/1.json
  def show
  end

  # GET /volunteers/new
  def new
    @volunteer = Volunteer.new
  end

  # GET /volunteers/1/edit
  def edit
  end

  # POST /volunteers or /volunteers.json
  def create
    @volunteer = Volunteer.new(volunteer_params)

    respond_to do |format|
      if @volunteer.save
        MagicLinkMailer.with(volunteer: @volunteer).welcome_email.deliver_later
        format.html { redirect_to @volunteer, notice: "Účet dobrovolníka byl úspěšně vytvořen." }
        format.json { render :show, status: :created, location: @volunteer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteers/1 or /volunteers/1.json
  def update
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to @volunteer, notice: "Účet dobrovolníka byl úspěšně upraven." }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def volunteer_params
      params.require(:volunteer).permit(:Příjmení, :Jméno, :Mail, :Telefon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Jméno %>
    <%= form.text_field :Jméno %>
  </div>

  <div class="field">
    <%= form.label :Příjmení %>
    <%= form.text_field :Příjmení %>
  </div>

  <div class="field">
    <%= form.label :Město %>
    <%= form.text_field :Město %>
  </div>

  <div class="field">
    <%= form.label :Ulice %>
    <%= form.text_field :Ulice %>
  </div>

  <div class="field">
    <%= form.label :ČP %>
    <%= form.text_field :ČP %>
  </div>

  <div class="field">
    <%= form.label :PSČ %>
    <%= form.text_field :PSČ %>
  </div>

  <div class="field">
    <%= form.label :Poznámka %>
    <%= form.text_field :Poznámka %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/new.html.erb
<h1>Nový Klient</h1>

<%= render 'form', client: @client %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Život 90", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "O nás", home_about_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        
      </ul>
      <div class="d-flex">
          <% if sign_up_signed_in? %>
            <li class="nav-item navbar-nav mb-2 mb-lg-0">
              <p class="nav-link nav-item navbar-nav mb-2 mb-lg-0"><strong><%= current_sign_up.email %></strong></p>
            </li>
            <li class="nav-item navbar-nav mb-2 mb-lg-0">
              <%= link_to 'Edit profile', edit_sign_up_registration_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item navbar-nav mb-2 mb-lg-0">
              <%= link_to "Logout", destroy_sign_up_session_path, method: :delete, :class => 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item navbar-nav mb-2 mb-lg-0">
              <%= link_to 'Sign up', new_sign_up_registration_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item navbar-nav mb-2 mb-lg-0">  
              <%= link_to "Login", new_sign_up_session_path, :class => 'nav-link' %>
            </li>
          <% end %>  
        </div>
      
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<br>
<center><h1>Ahoj, jsme tu, abychom Vám pomohli</h1></center>
<br>
<br>
<div class = "container">
    <center>
        <%= link_to "Chci pomáhat", new_volunteer_path ,class:"btn btn-secondary"%>
        <br>
        <br>
        <%= link_to "Potřebuji pomoci", new_order_path ,class:"btn btn-secondary"%>
        <br>
        <br>
        <%= link_to "Založit si klientský účet", new_client_path ,class:"btn btn-secondary"%>
    </center>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <title>RailsForGood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render "home/navbar"%>
  
  <body>
    <div class = "container">
      <br>
      <%= yield %>
    </div>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- Optional JavaScript; choose one of the two! -->
    
    
    
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<hr>
  <div class = "row">
    <div class="field mb-3 col form-group">
      <%= form.text_field :Jméno, class:"form-control", placeholder:"Jméno" %>
    </div>
    <div class="field mb-3 col form-group">
      <%= form.text_field :Příjmení, class:"form-control", placeholder:"Příjmení" %>
    </div>
  </div>
  <br>

  <div class = "row">
    <div class="field mb-3 col form-group">
      <%= form.text_field :Město, class:"form-control", placeholder:"Město" %>
    </div>
    <div class="field mb-3 col form-group">
      <%= form.text_field :Ulice, class:"form-control", placeholder:"Ulice" %>
    </div>
  </div>
  <div class =row>
    <div class="field mb-3 col form-group">
      <%= form.text_field :ČP, class:"form-control", placeholder:"Číslo Popisné" %>
    </div>

    <div class="field mb-3 col form-group">
      <%= form.text_field :PSČ, class:"form-control", placeholder:"PSČ" %>
    </div>
  </div>
  <br>

  <div class="field mb-3 col form-group">
    <%= form.text_field :Žádost, class:"form-control", placeholder:"Žádost" %>
  </div>
  <div class="field mb-3 col form-group">
    <%= form.text_field :Poznámka, class:"form-control", placeholder:"Poznámka" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-dark"%>
  </div>
<% end %>

app/views/orders/new.html.erb
<h1>Nová Žádost</h1>

<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<h1>Vaše žádost byla úspěšně odeslána</h1>
<hr>
<p>Až náš dobrovnolník žádost přijme, zašleme Vám bližšími informacemi</p>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/volunteers/_form.html.erb
<%= form_with(model: volunteer) do |form| %>
  <% if volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(volunteer.errors.count, "error") %> Tohoto dobrovolíka nelze uložit:</h2>

      <ul>
        <% volunteer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "row">
    <div class="field mb-3 col form-group">
      
      <%= form.text_field :Jméno, class:"form-control", placeholder:"Jméno" %>
    </div>
    <div class="field mb-3 col form-group">
            <%= form.text_field :Příjmení, class:"form-control", placeholder:"Příjmení" %>
    </div>
  </div>
  <div class = "row">
    <div class="field mb-3 col form-group">
      
      <%= form.text_field :Mail, class:"form-control", placeholder:"Mail" %>
    </div>

    <div class="field mb-3 col form-group">
      
      <%= form.text_field :Telefon, class:"form-control", placeholder:"Telefon" %>
    </div>
  </div>

  <div class="actions mb-3">
    <%= form.submit class:"btn btn-dark"%>
  </div>
<% end %>

app/views/volunteers/index.html.erb
<p>hello</p>

app/views/volunteers/new.html.erb
<h1>Nový Dobrovolník</h1>
<hr>

<%= render 'form', volunteer: @volunteer %>

app/views/volunteers/show.html.erb
<h1>Váš účet byl úspěšně vytvořen</h1>
<hr>
<p>Byl Vám odeslán uvítací E-mail s bižšími informacemi</p>